version: '3'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports: 
            - 8075:8075
        working_dir: /usr/src/app
        links:
            - mongodb
    mongodb:
        image: mongo
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
volumes:
    mongodb:
